### PR TITLE
Fix incompatibility with Hamlib 5.X

### LINKED ISSUE #91: Mercury 1.9.9 will not build against hamlib 5.x
Works on 4.6.5 but will not build against 5.x with this error:

make[1]: Entering directory '/home/mateo/mercury/radio_io' gcc -Wall -O2 -std=gnu11 -pthread -D_GNU_SOURCE -DGIT_HASH=\"2b473ee6\" -I/usr/local/include -I/usr/include/libusb-1.0 -DHAVE_HAMLIB -DHAVE_HERMES_SHM -c radio_io.c radio_io.c: In function ‘radio_io_init’: radio_io.c:149:23: error: ‘RIG’ {aka ‘struct s_rig’} has no member named ‘state’ 149 | snprintf(radio->state.rigport.pathname, HAMLIB_FILPATHLEN, "%s", device_path); | ^~ radio_io.c:153:14: error: ‘RIG’ {aka ‘struct s_rig’} has no member named ‘state’ 153 | radio->state.rigport.parm.serial.rate = serial_speed; | ^~ radio_io.c:174:14: error: ‘RIG’ {aka ‘struct s_rig’} has no member named ‘state’ 174 | radio->state.vfo_opt = rigctld_vfo_opt; | ^~ make[1]: *** [Makefile:66: radio_io.o] Error 1 make[1]: Leaving directory '/home/mateo/mercury/radio_io' make: *** [Makefile:156: internal_deps] Error 2 mateo@FZM1MK2:~/mercury

The build failure against Hamlib 5.0 is caused by API changes in the Hamlib 5 development branch, where function signatures (such as the removal or alteration of rig_get_info and VFO-handling functions) are incompatible with the older Hamlib bindings used in Mercury.

### PR DESCRIPTION
**Pull request by pedromessetti**
Fix #91

### CODE REVIEW

**Review by rafael2k — APPROVED** [review]
LGTM
